{
  "text-color": "#1F2328",
  "background-color": "#F0F8FF",
  "selection-background-color": "#B4D5FE",
  "link-color": "#0969DA",
  "keyword-color": "#CF222E",
  "comment-color": "#6E7781",
  "variable-color": "#0969DA",
  "type-color": "#953800",
  "function-color": "#8250DF",
  "string-color": "#0A3069",
  "number-color": "#0969DA",
  "attribute-color": "#953800",
  "class-color": "#953800",
  "error-color": "#CF222E"
}
